### ISSUE TITLE
Running Example

### ISSUE THREAD

**Issue by umadapuma** [inuex3/robot_mower_2dnav#1]
What exact steps would you go about doing to get an example of this running?

**Comment by inuex3** [comment]
Thank you for asking.
This project is still in development and I will work on it soon.

**Comment by umadapuma** [comment]
Thank you for the "Waypoint Generator usage". Would you need to run catkin_make in the files first then the rosrun's ?

**Comment by inuex3** [comment]
Yes, you need to build the heatmap client first with catkin make.

**Comment by umadapuma** [comment]
Do you mean like you normally would in the file with the src file? Also what version of ROS are you using, kinetic?

**Comment by inuex3** [comment]
The source code of the heat map client is in src, so you need to build it with catkin make. 
I use this package with melodic now but this can work with kinetic.

**Comment by umadapuma** [comment]
Hey, when I run rosrun robot_mower_2dnav heatmap_client it get ERROR failed to contact master at [localhost:11311]. Retrying...    Is there something I should be running before this command?

When I run roscore it says Please use 'Point' tool in Rviz but I'm not sure if there is somthing else that should run. 
Thank you so much .

**Comment by inuex3** [comment]
I think you can use teb local planner tutorial for convenience.
http://wiki.ros.org/teb_local_planner_tutorials
Run
roslaunch teb_local_planner_tutorials robot_diff_drive_in_stage.launch
The simulation will start and then run heatmap client and path planner.
The clicked points can be visualized by adding the topic in rviz.
Then draw a geographical figure with publish point.

**Comment by umadapuma** [comment]
O ok, I'll try this and I had shapely installed. Thank you.

**Comment by umadapuma** [comment]
How do you run the obstacle avoidance?

**Comment by inuex3** [comment]
In this packege, the obstacle avoidance can be done with teb local planner.
Look at http://wiki.ros.org/teb_local_planner_tutorials and teb_local_planner_params.yaml in cfg.
