### ISSUE TITLE
path_planner.py not launching

### ISSUE THREAD

**Issue by KishoreKaviarasu** [inuex3/robot_mower_2dnav#2]
/home/user/catkin_ws/src/robot_mower_2dnav/src/path_planner.py:63: SyntaxWarning: The publisher should be created with an explicit keyword argument 'queue_size'. Please see http://wiki.ros.org/rospy/Overview/Publishers%20and%20Subscribers for more information.
  latch=True)

**Comment by inuex3** [comment]
Actually this warning always appears... but it works. Try planning_test.launch
