### ISSUE TITLE
Can you wirte a   tutorial ， How is the video on YouTube implemented？

### ISSUE THREAD

**Issue by wangwenqiangGitHub** [inuex3/robot_mower_2dnav#3]
I run this package, but can‘t implement the video on YouTube

**Comment by inuex3** [comment]
I'm sorry that this package is not well maintained but I will when I have free time.
What kind of problems are you facing?
If you want to use planning, just use planning_test.launch

**Comment by wangwenqiangGitHub** [comment]
When I use oder " roslaunch  robot_mower_2dnav planning_test.launch “   the error is :
[publish_test_obstacles-8] process has died [pid 12730, exit code 1, cmd /home/kq/catkin_ws/src/robot_mower_2dnav/scripts/publish_test_obstacles.py /odom:=/base_pose_ground_truth __name:=publish_test_obstacles __log:=/home/kq/.ros/log/28aa4360-ec42-11ea-ba9c-105bad89ae71/publish_test_obstacles-8.log].
log file: /home/kq/.ros/log/28aa4360-ec42-11ea-ba9c-105bad89ae71/publish_test_obstacles-8*.log

**Comment by inuex3** [comment]
You can solve the second problem by installing mowing planner in my repository. 
https://github.com/inuex3/mowing_planner
As of the first one, take a look at robot_mower_2dnav/scripts/publish_test_obstacles.py and make sure you have installed the necessary packages.
